name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1) Checkout
        uses: actions/checkout@v4

      - name: 2) Generate 3D Profile
        uses: Platane/gh-profile-3d-contrib@master
        id: generator
        with:
          username: dev-snake
          output: 'profile-3d-contrib/profile-night-rainbow.svg'
          config: |
            {
              "palette": "rainbow"
            }

      - name: 3) Upload to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./profile-3d-contrib
