name: 3D Contribution Graph

on:
  schedule:
    - cron: "0 3 * * *"  # chạy mỗi ngày lúc 03:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1) Checkout repository
        uses: actions/checkout@v4

      - name: 2) Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@v1
        with:
          username: dev-snake               # tên GitHub của anh
          theme: rainbow                   # theme đẹp nhất
          filename: profile-night-rainbow  # tên file SVG (không cần .svg)
          output_dir: ./profile-3d-contrib # thư mục xuất file

      - name: 3) Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./profile-3d-contrib
          publish_branch: output
